name: Aggiorna Eventi Sportivi

on:
  schedule:
    # Esegui ogni giorno alle 06:00 e 18:00 CET
    - cron: '0 5,17 * * *'
  workflow_dispatch:  # Permette esecuzione manuale
  push:
    branches: [ main ]

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml

    - name: Run scraper
      run: |
        python scrape_events.py

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet eventi.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions Bot"
        git add eventi.json
        git commit -m "🔄 Aggiornamento automatico eventi sportivi - $(date +'%Y-%m-%d %H:%M')"
        git push
